# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: WaveNet-SIDD-width16_ConvNeXt_LIN_16_2288221_relu
model_type: ImageRestorationModel
scale: 1
num_gpu: 2
manual_seed: 10

datasets:
  train:
    name: SIDD
    type: PairedImageDataset
    dataroot_gt: ./data/SIDD/train/gt_crops.lmdb
    dataroot_lq: ./data/SIDD/train/input_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SIDD_val
    type: PairedImageDataset
    dataroot_gt: ./data/SIDD/val/gt_crops.lmdb
    dataroot_lq: ./data/SIDD/val/input_crops.lmdb
    io_backend:
      type: lmdb


network_g:
  type: WaveletNet
  mode: ConvNext # ConvNext, NAFBlock
  width: 16
  enc_blk_nums: [2, 2, 8]
  middle_blk_num: 8
  dec_blk_nums: [2, 2, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~ 

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [70000, 330000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.0000001]  

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: "NeoUnet-SIDD-ConvNext-U"
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
