name: WaveletNet-GT-Rain-width32_LocalConvNext_True_MIX_PARA
model_type: ImageRestorationModel
scale: 1
num_gpu: 2
manual_seed: 10

datasets:
# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: PairedImageDataset
    dataroot_gt: ./GT-RAIN/train/target
    dataroot_lq: ./GT-RAIN/train/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: PairedImageDataset
    dataroot_gt: ./GT-RAIN/val/target
    dataroot_lq: ./GT-RAIN/val/input
    io_backend:
      type: disk


network_g:
  type: WaveletNet
  width: 32
  enc_blk_nums: [4, 6, 6]
  middle_blk_num: 8
  dec_blk_nums: [4, 6, 6]
  G: "Identity" # ["Cswin", "CswinPool", "CswinPool_fix", "VanillaAttention", "Identity"]
  L: "LocalConvNeXt" # ["LocalAttention", "LocalCNN", "LocalConvNeXt", "Identity"]
  S: True # False, True

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~ 

# training settings
train:
  #  optim_g:
    #    type: AdamW
    #    lr: !!float 1e-3
    #    weight_decay: 0.
    #    betas: [0.9, 0.9]
    #
    #  scheduler:
    #    type: TrueCosineAnnealingLR
    #    T_max: 400000
    #    eta_min: !!float 1e-7
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [30000, 120000]       
    restart_weights: [1,1]
    eta_mins: [0.0002,0.000001]  

  total_iter: 150000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 15e3
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: "Wavelet-Rain13k"
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
